# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # an OS for the VM
  config.vm.box = "bento/centos-7.4"
  
  # name for the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Task-2-type2"
  end
  
  # configuring network for the vm
  config.vm.network "forwarded_port", guest: 80, host: 8050
  config.vm.network "private_network", ip: "192.168.56.5"

  # calling Ansible to provisioning the VM
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/playbook.yaml"
  end
end
