# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # an OS for the VM
  config.vm.box = "bento/centos-7.4"
  
  # name for the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Task-1"
  end

  # configuring network for the vm
  config.vm.network "forwarded_port", guest: 80, host: 8030
  config.vm.network "private_network", ip: "192.168.56.3"

end
