# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # an OS for the VM
  config.vm.box = "bento/centos-7.4"

  # name for the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Task-2-type1"
  end  
  
  # configuring network for the vm
  config.vm.network "forwarded_port", guest: 80, host: 8040
  config.vm.network "private_network", ip: "192.168.56.4"

  # mount folder with playbook for guest's Ansible
  config.vm.synced_folder "../../ansible", "/vagrant"

  # calling Ansible to provisioning the VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end
