# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # an OS for the VM
  config.vm.box = "bento/centos-7.4"
  
  # name for the VM
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Task-3"
  end
  
  # configuring network for the vm
  config.vm.network "forwarded_port", guest: 80, host: 8060
  config.vm.network "private_network", ip: "192.168.56.6"
  
  # adding custom public ssh key for accessing the VM:
  # - as an alternative way to connect to VM
  # - also as a future entrypoint for Ansible
  config.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/available.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/available.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL

end
  
